### ISSUE TITLE
Include FORCes experiments as compsets

### ISSUE THREAD

**Issue by gold2718** [NorESMhub/CAM#132]
### What is the feature/what would you like to discuss?

Bring in the FORCeS experiment 
In addition to the coupled compsets (see NorESMhub/NorESM#465), implement these AMIP compsets:

- `NF1850FORCeS`: FORCeS tunings
- `NFHISTFORCeS`: FORCeS tunings
- `NF1850norbcForces`: FORCeS tunings
- `NFHISTnorbc_aer2014Forces`: FORCeS tunings
- `NF1850`: KeyClim 1850 Cloud2
- `NFHIST`: KeyClim 1850 Cloud2

Details of code differences are in https://github.com/NorESMhub/CAM/discussions/108

### Will this change (regression test) answers?

Yes

### Will you be implementing this enhancement yourself?

Yes

**Comment by oyvindseland** [comment]
Re the discussion we have had on this topic in CAM-core meeting I think it is enough to have a complete set of parameterisations from Forces defined by default or namelist, which I do think we will have in NorESM2.3.1. I do not think it is necessary to create explicit compsets since the results will be different than Forces anyway. (Bug fixes and BLOM modifcations) I suggest to close the issue.
