### ISSUE TITLE
SOA yields 

### ISSUE THREAD

**Issue by sarambl** [NorESMhub/CAM#35]
Hi all, 
I cannot seem to find any reference for why the SOA yield for isoprene is 5%, anyone who knows? The 15 % for monoterpene seems to be from  Dentener et al (2006) which seems to have gotten it possibly from Kanakidou et al 2005 who say something like "let us assume that 15% ... )

More worrying from my side is that in the model, as far as I can tell, we use molar yields and not mass yields, while the litterature tends to present mass yields. E.g. for isoprene (which is much smaller than the assumed SOA_SV), the molar yield is set to 5 %, but that amounts to a mass yield of almost 12% if I am not mistaken. This is rather on the high end of what the litterature suggests. For monoterpenes, the difference is less because it is only assumed to gain 2 oxygen, which is percentwise only a 20% increase.

**Comment by MichaelSchulzMETNO** [comment]
Is the discussion and references given in Kirkevåg 2018 incomplete here?

**Comment by sarambl** [comment]
So, there's not really much discussion on this in Kirkevåg 2018, it just says that the yields are similar to other studies (Mann 2010, Tsigaridis 2014). Tsigaridis is for the 15 % from Dentener (2006) mentioned above, and the 5 % I am not sure where it comes from, but it is the same in ECHAM (maybe Risto had some influence in both developments?). However, I do not find a reference for the 5% in e.g. Jokinen 2015 either, but maybe I should look further back :) 

Conserning the mass-yield versus molar yield, I may be wrong, but all the lab studies I've seen use mass yields, see e.g. Shrivastava et al 2017, fig 5. I think Dentener is also talking mass yields, because they say 127 Tg/year of terpenes translate into 19.1 Tg POM/year (which is 15%).  I think that ECHAM also uses molar yields btw (at least we discussed this briefly when we wrote Sporre 2020). 
Maybe I have misunderstood something here? I feel like there is a lack of clarity on this in the litterature about assumptions both in yields and mass gain etc. 

(Mann et al 2010 use 13 % molar yield for terpenes, with mass gain of 12.5/11.3 from the reaction. This comment only if you are already down this rabbit hole.)

**Comment by MichaelSchulzMETNO** [comment]
I agree that there can be confusion on mola vs mass yields. I would believe experiments measure mass yields, but then - possibly the measurement is done with optical particle counters, so, I would suggest this is a topic to take up eg in FORCeS with the organic aerosol group indeed.

**Comment by sarambl** [comment]
Agreed :)

**Comment by MichaelSchulzMETNO** [comment]
Good that someone is questioning the yields!

I can answer partly, purely from my perspective for now (don't have time for a better review here). Perhaps interesting, although not very useful.

When I started making the SOA model for ECHAM-HAM (in 2006), I used the same assumptions as Philip in original ECHAM-HAM: "The biogenic monoterpene emissions of Guenther et al. (1995), are scaled by the factor 0.15 to estimate the production of Secondary Organic Aerosol (SOA) from biogenic sources (ACB)." (Stier et al., 2005)

Why did Philip use a scaling factor of 0.15 was not apparent from the paper. Anyhow at this point (in 2006), there was very little to back up other choices that would be exceptionally more realistic. Marias SOA review provided a bit insight to potential variability in the yields:

   https://acp.copernicus.org/articles/5/1053/2005/acp-5-1053-2005.pdf

In the meantime, GLOMAP was using 10% or 13% yields (same precursor emissions):

"We assume a 10% hydrophilic carbon yield of OC from terpenes (Chin et al., 2002) with emissions calculated according to Guenther et al. (1995). " (Spracklen et al., 2008a)

and

"We assume that the first‐stage oxidation products of monoterpenes [Guenther et al., 1995] form hydrophilic secondary organic aerosol (SOA) with a yield of 13% [Spracklen et al., 2006]. " (Spracklen et al., 2008b)
It is apparent from Tsigaridis (2014) review that a similar assumption (with Guenther 1995) was used by majority of models (check table 1). We started developing further the MT speciation and the different oxidation pathways of the precursors, and made much more detailed assumptions on the yields of ELVOCs/HOMs (Jokinen et al. 2014) and this was partly brought to NorESM as well, right?

For isoprene, I guess it is even more hand-waving, since you would like to have more detailed (and multi-phase) chemistry, and partitioning between aerosol-gas phase. In this scheme we have chosen 5% effective yield, you can find e.g. 6% in CAM-MAM3. We have analyzed the SOA formation from isoprene this way, but it is hard to constrain.

And of course, there's a lot of hand-waving going in to the yields, first choosing the base-yield, say 10% or 15%, then multiplying that yield by another made-up-factor to get e.g. the anthropogenic influence on the yield (say 1.5x).

So let's hope we can do this better in FORCeS!

Risto
