### ISSUE TITLE
Add all code for KeyClim experiment balanced cloud experiments to github

### ISSUE THREAD

**Issue by oyvindseland** [NorESMhub/CAM#93]
### Issue Type

Code Clean-up, Infrastructure Update

### Issue Description

Some of the code used for experiments is still on SourceMods under the experiment and should be pushed to the branch
Changes in namelist should be defined as a user mod?
After disucssion: Should the code changes be included in the main NorESM / or NorESM-KeyClim branch as a namelist option or should it stay at a private fork?

The modified code changes the climate of the model when turned on.
The modified code is bit-identical if the modifications are turned off.

### Will this change answers?

Yes

### Will you be implementing this yourself?

Yes

**Comment by gold2718** [comment]
This issue was resolved by [NorESM/#462](https://github.com/NorESMhub/NorESM/pull/462)
The modifications are now available as a user-mod (cime_config/usermods_dirs/cmip6_noresm_keyCLIM_cloud2).
To use this in a simulation, add the following to a `create_newcase` call:
CAM checkout: `--user-mods-dir cime_<root>/config/usermods_dirs/cmip6_noresm_keyCLIM_cloud2`
NorESM checkout: `--user-mods-dir cime_<root>/components/cam/config/usermods_dirs/cmip6_noresm_keyCLIM_cloud2`
